services:
  postgres:
    image: postgres:16
    container_name: taskify-postgres
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: taskify-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma

  frontend:
    build: ./frontend
    container_name: taskify-frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

volumes:
  postgres_data:
